CREATE TABLE
	"prompt_reviews_review_flags" (
		"prompt_review_id" integer NOT NULL,
		"flag_id" integer NOT NULL,
		CONSTRAINT "prompt_reviews_review_flags_prompt_review_id_flag_id_pk" PRIMARY KEY ("prompt_review_id", "flag_id")
	);

--> statement-breakpoint
CREATE TABLE
	"prompt_reviews" (
		"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
			sequence name "prompt_reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START
			WITH
				1 CACHE 1
		),
		"user_id" uuid NOT NULL,
		"opinion" varchar(8) NOT NULL,
		"comment" text NOT NULL,
		"prompt_id" uuid NOT NULL,
		"created_at" timestamp DEFAULT now () NOT NULL
	);

--> statement-breakpoint
CREATE TABLE
	"review_flags" (
		"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
			sequence name "review_flags_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START
			WITH
				1 CACHE 1
		),
		"flag" varchar(50) NOT NULL,
		"opinion" varchar(8),
		CONSTRAINT "review_flags_flag_unique" UNIQUE ("flag")
	);

--> statement-breakpoint
CREATE TABLE
	"test_result_reviews_review_flags" (
		"test_result_review_id" integer NOT NULL,
		"flag_id" integer NOT NULL,
		CONSTRAINT "test_result_reviews_review_flags_test_result_review_id_flag_id_pk" PRIMARY KEY ("test_result_review_id", "flag_id")
	);

--> statement-breakpoint
CREATE TABLE
	"test_result_reviews" (
		"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
			sequence name "test_result_reviews_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START
			WITH
				1 CACHE 1
		),
		"user_id" uuid NOT NULL,
		"opinion" varchar(8) NOT NULL,
		"comment" text NOT NULL,
		"test_result_id" integer NOT NULL,
		"created_at" timestamp DEFAULT now () NOT NULL
	);

--> statement-breakpoint
DROP TABLE "feedback_flags" CASCADE;

--> statement-breakpoint
DROP TABLE "feedbacks_feedback_flags" CASCADE;

--> statement-breakpoint
DROP TABLE "feedbacks" CASCADE;

--> statement-breakpoint
DROP TABLE "prompt_feedbacks" CASCADE;

--> statement-breakpoint
DROP TABLE "test_result_feedbacks" CASCADE;

--> statement-breakpoint
ALTER TABLE "prompt_reviews_review_flags" ADD CONSTRAINT "prompt_reviews_review_flags_prompt_review_id_prompt_reviews_id_fk" FOREIGN KEY ("prompt_review_id") REFERENCES "public"."prompt_reviews" ("id") ON DELETE cascade ON UPDATE cascade;

--> statement-breakpoint
ALTER TABLE "prompt_reviews_review_flags" ADD CONSTRAINT "prompt_reviews_review_flags_flag_id_review_flags_id_fk" FOREIGN KEY ("flag_id") REFERENCES "public"."review_flags" ("id") ON DELETE cascade ON UPDATE cascade;

--> statement-breakpoint
ALTER TABLE "prompt_reviews" ADD CONSTRAINT "prompt_reviews_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users" ("id") ON DELETE cascade ON UPDATE cascade;

--> statement-breakpoint
ALTER TABLE "prompt_reviews" ADD CONSTRAINT "prompt_reviews_prompt_id_prompts_id_fk" FOREIGN KEY ("prompt_id") REFERENCES "public"."prompts" ("id") ON DELETE cascade ON UPDATE cascade;

--> statement-breakpoint
ALTER TABLE "test_result_reviews_review_flags" ADD CONSTRAINT "test_result_reviews_review_flags_test_result_review_id_test_result_reviews_id_fk" FOREIGN KEY ("test_result_review_id") REFERENCES "public"."test_result_reviews" ("id") ON DELETE cascade ON UPDATE cascade;

--> statement-breakpoint
ALTER TABLE "test_result_reviews_review_flags" ADD CONSTRAINT "test_result_reviews_review_flags_flag_id_review_flags_id_fk" FOREIGN KEY ("flag_id") REFERENCES "public"."review_flags" ("id") ON DELETE cascade ON UPDATE cascade;

--> statement-breakpoint
ALTER TABLE "test_result_reviews" ADD CONSTRAINT "test_result_reviews_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "auth"."users" ("id") ON DELETE cascade ON UPDATE cascade;

--> statement-breakpoint
ALTER TABLE "test_result_reviews" ADD CONSTRAINT "test_result_reviews_test_result_id_test_results_id_fk" FOREIGN KEY ("test_result_id") REFERENCES "public"."test_results" ("id") ON DELETE cascade ON UPDATE cascade;