CREATE TABLE
	"supporting_document_prompt_sets" (
		"document_id" integer NOT NULL,
		"prompt_set_id" integer NOT NULL,
		"created_at" timestamp DEFAULT now () NOT NULL,
		CONSTRAINT "supporting_document_prompt_sets_document_id_prompt_set_id_pk" PRIMARY KEY ("document_id", "prompt_set_id")
	);

--> statement-breakpoint
CREATE TABLE
	"supporting_documents" (
		"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (
			sequence name "supporting_documents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START
			WITH
				1 CACHE 1
		),
		"name" text NOT NULL,
		"content" text NOT NULL,
		"cid" text NOT NULL,
		"sha256" text NOT NULL,
		"uploader_id" uuid NOT NULL,
		"is_public" boolean DEFAULT false NOT NULL,
		"created_at" timestamp DEFAULT now () NOT NULL,
		"updated_at" timestamp DEFAULT now () NOT NULL,
		CONSTRAINT "supporting_documents_cid_unique" UNIQUE ("cid")
	);

--> statement-breakpoint
ALTER TABLE "supporting_document_prompt_sets" ADD CONSTRAINT "supporting_document_prompt_sets_document_id_supporting_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."supporting_documents" ("id") ON DELETE cascade ON UPDATE cascade;

--> statement-breakpoint
ALTER TABLE "supporting_document_prompt_sets" ADD CONSTRAINT "supporting_document_prompt_sets_prompt_set_id_prompt_sets_id_fk" FOREIGN KEY ("prompt_set_id") REFERENCES "public"."prompt_sets" ("id") ON DELETE cascade ON UPDATE cascade;

--> statement-breakpoint
ALTER TABLE "supporting_documents" ADD CONSTRAINT "supporting_documents_uploader_id_users_id_fk" FOREIGN KEY ("uploader_id") REFERENCES "auth"."users" ("id") ON DELETE cascade ON UPDATE cascade;

-- Create indexes for better performance
CREATE INDEX "idx_supporting_documents_uploader_id" ON "supporting_documents" ("uploader_id");

CREATE INDEX "idx_supporting_documents_is_public" ON "supporting_documents" ("is_public");

CREATE INDEX "idx_supporting_documents_created_at" ON "supporting_documents" ("created_at");

CREATE INDEX "idx_supporting_document_prompt_sets_document_id" ON "supporting_document_prompt_sets" ("document_id");

CREATE INDEX "idx_supporting_document_prompt_sets_prompt_set_id" ON "supporting_document_prompt_sets" ("prompt_set_id");