DROP VIEW "public"."v_users";--> statement-breakpoint
CREATE OR REPLACE VIEW "public"."v_review_contributors_per_prompt_set" AS (select "prompt_set_id", "user_id", "contribution_type" from (((select "prompt_set_prompts"."prompt_set_id", "quick_feedbacks"."user_id", 'prompt' as "contribution_type" from "prompt_set_prompts" left join "prompts" on "prompts"."id" = "prompt_set_prompts"."prompt_id" inner join "quick_feedbacks" on "quick_feedbacks"."prompt_id" = "prompts"."id" where "prompt_set_prompts"."status" = 'included') union (select "prompt_set_prompts"."prompt_set_id", "quick_feedbacks"."user_id", 'response' as "contribution_type" from "prompt_set_prompts" left join "responses" on "responses"."id" = "prompt_set_prompts"."prompt_id" inner join "quick_feedbacks" on "quick_feedbacks"."response_id" = "responses"."id" where "prompt_set_prompts"."status" = 'included')) union (select "prompt_set_prompts"."prompt_set_id", "quick_feedbacks"."user_id", 'score' as "contribution_type" from "prompt_set_prompts" left join "scores" on "scores"."id" = "prompt_set_prompts"."prompt_id" inner join "quick_feedbacks" on "quick_feedbacks"."score_id" = "scores"."id" where "prompt_set_prompts"."status" = 'included')) "query" group by "query"."user_id", "query"."prompt_set_id", "contribution_type");--> statement-breakpoint
CREATE OR REPLACE VIEW "public"."v_upload_contributors_per_prompt_set" AS (select "id", "uploader_id", "collaboration_type" from (((select "prompt_sets"."id", "prompts"."uploader_id", 'prompt' as "collaboration_type" from "prompt_sets" inner join "prompt_set_prompts" on ("prompt_set_prompts"."prompt_set_id" = "prompt_sets"."id" and "prompt_set_prompts"."status" = 'included') inner join "prompts" on "prompts"."id" = "prompt_set_prompts"."prompt_id") union (select "prompt_sets"."id", "responses"."uploader_id", 'response' as "collaboration_type" from "prompt_sets" inner join "prompt_set_prompts" on ("prompt_set_prompts"."prompt_set_id" = "prompt_sets"."id" and "prompt_set_prompts"."status" = 'included') inner join "responses" on "responses"."id" = "prompt_set_prompts"."prompt_id")) union (select "prompt_sets"."id", "scores"."uploader_id", 'score' as "collaboration_type" from "prompt_sets" inner join "prompt_set_prompts" on ("prompt_set_prompts"."prompt_set_id" = "prompt_sets"."id" and "prompt_set_prompts"."status" = 'included') inner join "scores" on "scores"."id" = "prompt_set_prompts"."prompt_id")) "query" group by "query"."uploader_id", "query"."id", "collaboration_type");--> statement-breakpoint
CREATE OR REPLACE VIEW "public"."v_overall_score_per_prompt_set" AS (select "prompt_set_prompts"."prompt_set_id", count("scores"."id") as "total_score_count", sum("scores"."score") as "total_score", avg("scores"."score") as "avg_score" from "prompt_set_prompts" left join "scores" on "scores"."prompt_id" = "prompt_set_prompts"."prompt_id" where "prompt_set_prompts"."status" = 'included' group by "prompt_set_prompts"."prompt_set_id");--> statement-breakpoint
CREATE OR REPLACE VIEW "public"."v_prompt_set_stats" AS (select "prompt_sets"."id", 
        COUNT(DISTINCT "prompt_set_prompts"."prompt_id")
        FILTER (WHERE "prompt_set_prompts"."status" = 'included')
       as "included_prompt_count", 
        COUNT(DISTINCT "prompt_set_prompts"."prompt_id")
        FILTER (WHERE "prompt_set_prompts"."status" = 'excluded')
       as "excluded_prompt_count", "total_score_count", "avg_score", 
        COALESCE(count(distinct "v_upload_contributors_per_prompt_set"."uploader_id"), 0) +
        COALESCE(count(distinct "v_review_contributors_per_prompt_set"."user_id"), 0) +
        COALESCE(count(distinct "user_role_on_prompt_set"."user_id"), 0)
       as "total_contributors" from "prompt_sets" left join "prompt_set_prompts" on "prompt_set_prompts"."prompt_set_id" = "prompt_sets"."id" left join "v_upload_contributors_per_prompt_set" on "v_upload_contributors_per_prompt_set"."id" = "prompt_sets"."id" left join "v_review_contributors_per_prompt_set" on "v_review_contributors_per_prompt_set"."prompt_set_id" = "prompt_sets"."id" left join "v_overall_score_per_prompt_set" on "v_overall_score_per_prompt_set"."prompt_set_id" = "prompt_sets"."id" left join "user_role_on_prompt_set" on "user_role_on_prompt_set"."prompt_set_id" = "prompt_sets"."id" group by "prompt_sets"."id", "total_score_count", "avg_score");--> statement-breakpoint
CREATE OR REPLACE VIEW "public"."v_users" AS (select "auth"."users"."id", "auth"."users"."email", "auth"."users"."last_sign_in_at", "user_profile"."display_name", "orgs"."name", "orgs"."country", "orgs"."id" as "org_id", "user_profile"."github", "user_profile"."website", "user_profile"."bluesky", "user_profile"."mastodon", "user_profile"."twitter", "user_profile"."created_at", "user_profile"."updated_at" from "auth"."users" inner join "user_profile" on "user_profile"."user_id" = "auth"."users"."id" left join "org_to_people" on "org_to_people"."user_id" = "auth"."users"."id" left join "orgs" on "orgs"."id" = "org_to_people"."org_id");