DROP VIEW "public"."v_current_model_elo";--> statement-breakpoint
DROP VIEW "public"."v_current_model_performance";--> statement-breakpoint
ALTER TABLE "ranking_model_elo" DROP CONSTRAINT "ranking_model_elo_computation_id_model_unique";--> statement-breakpoint
ALTER TABLE "ranking_model_performance" DROP CONSTRAINT "ranking_model_performance_computation_id_model_unique";--> statement-breakpoint
ALTER TABLE "ranking_model_elo" ADD COLUMN "provider_model_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "ranking_model_performance" ADD COLUMN "provider_model_id" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "ranking_model_elo" ADD CONSTRAINT "ranking_model_elo_provider_model_id_provider_models_id_fk" FOREIGN KEY ("provider_model_id") REFERENCES "public"."provider_models"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ranking_model_performance" ADD CONSTRAINT "ranking_model_performance_provider_model_id_provider_models_id_fk" FOREIGN KEY ("provider_model_id") REFERENCES "public"."provider_models"("id") ON DELETE cascade ON UPDATE cascade;--> statement-breakpoint
ALTER TABLE "ranking_model_elo" DROP COLUMN "model";--> statement-breakpoint
ALTER TABLE "ranking_model_performance" DROP COLUMN "model";--> statement-breakpoint
ALTER TABLE "ranking_model_elo" ADD CONSTRAINT "ranking_model_elo_computation_id_provider_model_id_unique" UNIQUE("computation_id","provider_model_id");--> statement-breakpoint
ALTER TABLE "ranking_model_performance" ADD CONSTRAINT "ranking_model_performance_computation_id_provider_model_id_unique" UNIQUE("computation_id","provider_model_id");--> statement-breakpoint
CREATE VIEW "public"."v_current_model_elo" AS (select "ranking_model_elo"."provider_model_id", "provider_models"."model_id", "ranking_model_elo"."elo_score", "ranking_model_elo"."win_count", "ranking_model_elo"."loss_count", "ranking_model_elo"."match_count", "ranking_computations"."computed_at" from "ranking_model_elo" inner join "ranking_computations" on "ranking_model_elo"."computation_id" = "ranking_computations"."id" inner join "provider_models" on "ranking_model_elo"."provider_model_id" = "provider_models"."id" where "ranking_model_elo"."computation_id" = (SELECT "latest"."id" FROM (select "id" from "ranking_computations" order by "ranking_computations"."computed_at" DESC limit 1) "latest"));--> statement-breakpoint
CREATE VIEW "public"."v_current_model_performance" AS (select "ranking_model_performance"."provider_model_id", "provider_models"."model_id", "ranking_model_performance"."score", "ranking_model_performance"."prompts_tested_count", "ranking_computations"."computed_at" from "ranking_model_performance" inner join "ranking_computations" on "ranking_model_performance"."computation_id" = "ranking_computations"."id" inner join "provider_models" on "ranking_model_performance"."provider_model_id" = "provider_models"."id" where "ranking_model_performance"."computation_id" = (SELECT "latest"."id" FROM (select "id" from "ranking_computations" order by "ranking_computations"."computed_at" DESC limit 1) "latest"));