# Get the env file from the secrets api
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/$_ENV_SECRET_NAME/versions/latest
      env: "ENV_FILE"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Write env secret to a tmp file
  - name: "ubuntu"
    secretEnv: ["ENV_FILE"]
    script: |
      set -euo pipefail
      umask 077 # R/W only for the owner
      printf '%s' "$ENV_FILE" > /workspace/.env

  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    env:
      - "DOCKER_BUILDKIT=1"
    args:
      - "build"
      - "-f"
      - "Dockerfile.webapp"
      - "--secret"
      - "id=env,src=/workspace/.env"
      - "-t"
      - "$_AR_HOSTNAME-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - "."

  # Push container to the Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "$_AR_HOSTNAME-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/$_SERVICE_NAME"

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy "$_SERVICE_NAME" \
          --image "$_AR_HOSTNAME-docker.pkg.dev/$PROJECT_ID/$_AR_REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA" \
          --region "$_REGION" \
          --platform "managed"
