export const PEERBENCH_ERROR_CODES = {
  PROVIDER_FORWARD_FAILED: "PROVIDER_FORWARD_FAILED",
  PROVIDER_UNAUTHORIZED: "PROVIDER_UNAUTHORIZED",
  PROVIDER_MAX_RETRIES_REACHED: "PROVIDER_MAX_RETRIES_REACHED",
} as const;
export type PeerBenchErrorCode =
  (typeof PEERBENCH_ERROR_CODES)[keyof typeof PEERBENCH_ERROR_CODES];
